// Blurbs entries — Opera Obscura bibliography (SOURCE OF TRUTH; safe to hand-edit).
// Add new entries anywhere; run the search repo's Scripts/Extraction/OperaObscura/
// normalize_texts.py to re-sort by year + mint a stable id for any new entry.

export const blurbs = [
    {
        id: "k25prn",
        title: "Blurb for <i>Essays Presented to Charles Williams</i>",
        printedIn: "<i>Essays Presented to Charles Williams,</i> ed. C.S. Lewis (Oxford: Oxford University Press)",
        issueOrVolume: null,
        pageRange: "dust jacket",
        year: 1947,
        monthAndDay: null,
        textProvided: "In this book the reader is offered the work of one professional author, two dons, a solicitor, a friar, and a retired army officer: or, again, and by another classification, the work of one Anglo-Catholic, two Papists, an anthroposophist, and two whose profession is old-fashioned, square-rigged “C. of E.”, and if the reader feels disposed to complain of hotch-potch, I must reply that the variety displayed by this little group is far too small to represent the width of Charles Williams’s friendships.",
        type: "Blurb",
        notes: ["Compare the blurb with the first sentence of Lewis’s preface to <i>Essays Presented to Charles Williams</i>: “In this book the reader is offered the work of one professional author, two dons, a solicitor, a friar, and a retired army officer; if he feels disposed to complain of hotch-potch (which incidentally is an excellent dish; consult the Noctes Ambrosianae) I must reply that the variety displayed by this little group is far too small to represent the width of Charles Williams’s friendships.” That preface is itself reprinted in <i>Image and Imagination,</i> ed. Walter Hooper, (Cambridge: Cambridge University Press), 110-124, item 18.", "The text of the front flap is reprinted in its entirety in Walter Hooper, “A Bibliography of the Writings of C.S. Lewis” in <i>Remembering C.S. Lewis: Recollections of Those Who Knew Him,</i> 3<sup>rd</sup> edition, ed. James T. Como (San Francisco: Ignatius, 2005), 466, item G21."]
    },
    {
        id: "vet72j",
        title: "Blurb for <i>A New Translation of the Bible: Containing the Old and New Testaments,</i> trans. James Moffatt (London: Hodder and Stoughton, 1925; revised edition, 1935)",
        printedIn: "<i>The Guardian</i>",
        issueOrVolume: null,
        pageRange: "3",
        year: 1949,
        monthAndDay: "10 June",
        textProvided: "Begin with the N.T. and not with the books about it. If you do not know Greek, get it in a modern translation. Moffatt’s is probably the best[.]",
        type: "Blurb",
        notes: ["This text is taken from <i>Miracles,</i> the beginning of chapter 17 (“Epilogue”), with some minor alterations: “My work ends here. If, after reading it, you now turn to study the historical evidence for yourself, begin with the New Testament and not with the books about it. If you do not know Greek get it in a modern translation. Moffat’s [sic] is probably the best: Monsignor Knox is also good. I do not advise the <i>Basic English</i> version.”"]
    },
    {
        id: "8zxq9r",
        title: "Blurb for John Custance, <i>Wisdom, Madness & Folly: The Philosophy of a Lunatic</i> (London: Victor Gollancz, 1951)",
        printedIn: "<i>The Daily Telegraph & Morning Post</i>",
        issueOrVolume: null,
        pageRange: "14",
        year: 1951,
        monthAndDay: "11 May",
        textProvided: "I do not think I shall ever forget the experience of reading it.",
        type: "Blurb",
        notes: ["The dust jacket for this edition does not contain any comment by Lewis, nor does that of the American edition (New York: Pellegrini & Cudahy, 1952).", "The same endorsement also appeared two weeks later in <i>The Daily Telegraph & Morning Post</i> (25 May 1951), 6, and twice in <i>The Observer</i> (13 May 1951), 4, and (17 June 1951), 4."]
    },
    {
        id: "w8hfyf",
        title: "Blurb for Nancy Wilson Ross, <i>Time’s Corner</i> (London: Collins, 1953)",
        printedIn: "<i>The Observer</i>",
        issueOrVolume: null,
        pageRange: "7",
        year: 1951,
        monthAndDay: "16 August",
        textProvided: "I enjoyed it greatly[.]",
        type: "Blurb",
        notes: ["This text is from an unpublished letter to Ross (25 October 1952) in the Nancy Wilson Ross Papers (Box 24.2, Series I, Subseries A), Harry Ransom Center, The University of Texas at Austin. Ross had written to Lewis on 5 October 1952, sending him a copy of <i>Time’s Corner,</i> and telling him of the origin of its title, which is a phrase from <i>Perelandra.</i>"]
    },
    {
        id: "gn9drn",
        title: "Blurb for a Religious of C.S.M.V., <i>The Coming of the Lord: A Study in the Creed</i>",
        printedIn: "A Religious of C.S.M.V., <i>The Coming of the Lord: A Study in the Creed</i> (London: A.R. Mowbray)",
        issueOrVolume: null,
        pageRange: "dust jacket front flap",
        year: 1953,
        monthAndDay: null,
        textProvided: "I am delighted with <i>The Coming of the Lord</i>: delighted, excited, and most grateful. I think it is the best book the author has yet done, and the best theological book by any one I have read for a long time […] A lovely little book.",
        type: "Blurb",
        notes: ["Reprinted in <i>Remembering C.S. Lewis: Recollections of Those Who Knew Him</i>, 3rd edition, ed. James T. Como (San Francisco: Ignatius, 2005), 469, item G40, with minor punctuation differences.","The text is ultimately based on a letter to Sister Penelope CSMV, 4 January 1953, found in <i>CL</i> 3:316-318: “I am simply <i>delighted</i> with <i>The Coming of the Lord</i>; delighted, excited, and most grateful. I think it is the best book you have yet done, and the best theological book by anyone I have read for a long time. (You are, among other things, the only person I ever meet who gives me real light on the Old Testament.) …[318] Anyway, it is a lovely little book. I am very much in your debt.”"]
    },
    {
        id: "qvme49",
        title: "Blurb for Arthur C. Clarke, <i>Childhood’s End</i> ",
        printedIn: "Arthur C. Clarke, <i>Childhood’s End</i> (London: Sidgwick and Jackson)",
        issueOrVolume: null,
        pageRange: "dust jacket front flap",
        year: 1954,
        monthAndDay: null,
        textProvided: "It is quite out of range of the common space-and-time writers; away up near Lindsay’s <i>Voyage to Arcturus</i> and Wells’s <i>First Men in the Moon</i>. It hasn’t got Ray Bradbury’s delicacy, but then it has ten times his emotional power. …It’s rather like the effect of the <i>Ring</i>—a self-riching work, harmony piling up on harmony, grandeur on grandeur, pity on pity. …The first climax brought tears to my eyes. There has been nothing like it for years; partly for the actual invention, but partly because here we meet a modern author who understands that there may be things that have a higher claim on humanity than its own ‘survival’.",
        type: "Blurb",
        notes: ["This 110-word text is derived from <i>CL</i> 3:390-391 to Joy Gresham (not to Clarke, who only heard about the letter later after meeting Joy in person in New York), with some unmarked omissions and even a significant word change (“the actual writing” in <i>CL</i> 3:391 becomes “the actual invention” in the blurb).", "There are four other known variations of this blurb. An 18-word version appeared in newspaper advertisements from late April to early May 1954: “It is quite out of range of the common space-and-time writers…there has been nothing like it for years.” <i>The Observer</i> (25 April 1954), 9 and <i>The Birmingham Post</i> (27 April 1954), 6 omit the final period, but <i>The Western Mail</i> (28 April 1954), 6 and <i>The Liverpool Daily Post</i> (4 May 1954), 9 include it.", "A 65-word version was printed in an advertisement for <i>Childhood’s End</i> in the 7 May 1954 edition of <i>The Guardian:</i> “It is quite out of range of the common space-and-time writers; away up near Lindsay’s <i>Voyage to Arcturus</i> and Wells’s <i>First Men in the Moon</i>…There has been nothing like it for years; partly for the actual invention, but partly because here we meet a modern author who understands that there may be things that have a higher claim on humanity than its own ‘survival’.”", "A 27-word version was used on the back cover of the 1956 Pan paperback edition, according to Walter Hooper in <i>CL</i> 3:410, note 39: “There has been nothing like it for years…an author who understands there may be things that have a higher claim on humanity than its own survival.”", "However, this version differs from the 16-word variation on 1956 Pan paperback printing I have seen: “The first climax brought tears to my eyes. There has been nothing like it for years.”"]
    },
    {
        id: "bzfezb",
        title: "Blurb for J.R.R. Tolkien, <i>The Fellowship of the Ring</i>",
        printedIn: "J.R.R. Tolkien, <i>The Fellowship of the Ring: Being the First Part of the Lord of the Rings</i> (London: George Allen and Unwin)",
        issueOrVolume: null,
        pageRange: "dust jacket front flap",
        year: 1954,
        monthAndDay: null,
        textProvided: "If Ariosto rivalled it in invention (in fact he does not) he would still lack its heroic seriousness. No imaginary world has been projected which is at once multifarious and so true to its own inner laws; none so seemingly objective, so disinfected from the taint of an author’s merely individual psychology; none so relevant to the actual human situation yet so free from allegory. And what fine shading there is in the variations of style to meet the almost endless diversity of scenes and characters–comic, homely, epic, monstrous, or diabolic.",
        type: "Blurb",
        notes: ["From <i>CL</i> 3:383 to Stanley Unwin (4 December 1953). The blurb portion of this letter, along with a holograph of it, is reprinted in <i>Life and Legend: An Exhibition to Commemorate the Centenary of the Birth of J.R.R. Tolkien (1892-1973)</i> (Oxford: Bodleian Library, 1992), 62."]
    },
    {
        id: "jusekt",
        title: "Blurb for Robert Penn Warren, <i>Brother to Dragons</i> (London: Eyre and Spottiswoode, 1953)",
        printedIn: "<i>The Guardian</i>",
        issueOrVolume: null,
        pageRange: "6",
        year: 1954,
        monthAndDay: "29 June",
        textProvided: "A work modern in its grimness but classical in its sanity, which displays (especially in its architectonics) very high powers of invention.",
        type: "Blurb",
        notes: ["The dust jacket for this edition does not contain any comment by Lewis, nor does that of the American edition (New York: Random House, 1953)."]
    },
    {
        id: "5vr4qm",
        title: "Blurb for Harry Blamires, <i>Blessing Unbounded</i> (London: Longmans, Green and Company, 1955)",
        printedIn: "<i>The Observer</i>",
        issueOrVolume: null,
        pageRange: "10",
        year: 1955,
        monthAndDay: "18 December",
        textProvided: "This last one is definitely the best of the three…I admire the way he leads us time after time up the garden path; each time you think you’re in for a well-worn type of ridicule directed against a too familiar target, and each time you find that the purpose is quite different.",
        type: "Blurb",
        notes: ["See <i>CL</i> 3:682 note 367 for an indirect record of the text.", "The dust jacket for this edition does not contain any comment by Lewis."]
    },
    {
        id: "smghrc",
        title: "Blurb for Joy Davidman, <i>Smoke on the Mountain: An Interpretation of the Ten Commandments</i> (London: Hodder and Stoughton, 1955)",
        printedIn: "<i>The Guardian</i>",
        issueOrVolume: null,
        pageRange: "8",
        year: 1955,
        monthAndDay: "23 February",
        textProvided: "The quality of this book lies in its union of passionate heat with intelligence.",
        type: "Blurb",
        notes: ["From Lewis’s foreword, 10-11: “On the contrary the quality in this book which, I anticipate, will stand out more clearly the better it is known, is precisely the union of passionate heat with an intelligence which, in that passion, still modifies and distinguishes and tempers.”"]
    },
    {
        id: "8faf2p",
        title: "Blurb for Martyn Skinner, <i>The Return of Arthur: A Poem of the Future</i>",
        printedIn: "Martyn Skinner, <i>The Return of Arthur: A Poem of the Future</i> (London: Chapman and Hall)",
        issueOrVolume: null,
        pageRange: "dust jacket front flap",
        year: 1955,
        monthAndDay: null,
        textProvided: "I’ve romped through it with unflagging interest: a good, stiff sea-breeze of a poem which fills the lungs and makes one hold one’s hat on.",
        type: "Blurb",
        notes: ["Text is derived from <i>CL</i> 3:570 to Martyn Skinner, 27 February 1955: “I’ve romped thro’ it with unflagging interest: a good, stiff sea-breeze of a poem which fills the lungs and makes one hold one’s hat on. (There: but hesitate for using it as a blurb. My blurb did Tolkien’s <i>Lord of the Rings</i>—wh. is glorious, I hope you’ve read it—more harm than good).”", "The blurb is reprinted on Martyn Skinner, <i>The Return of Arthur: A Poem of the Future, Part 2</i> (London: Chapman and Hall, 1959), dust jacket back cover."]
    },
    {
        id: "m884e3",
        title: "Blurb for Clare Kipps, <i>Sold for a Song</i> (London: Frederick Muller Ltd, 1956)",
        printedIn: "<i>The Daily Telegraph and Morning Post</i>",
        issueOrVolume: null,
        pageRange: "10",
        year: 1956,
        monthAndDay: "15 June",
        textProvided: "Every bit as good as its predecessor, and perhaps even more interesting.",
        type: "Blurb",
        notes: ["The dust jacket for this edition does not contain any comment by Lewis."]
    },
    {
        id: "h45zsc",
        title: "Blurb for Katharine M. Briggs, <i>Hobberdy Dick</i> (London: Eyre & Spottiswoode, 1955)",
        printedIn: "<i>The Observer</i>",
        issueOrVolume: null,
        pageRange: "12",
        year: 1956,
        monthAndDay: "8 January",
        textProvided: "What a splendid conception! How many people would have given their teeth to have thought of it. The ending is deeply satisfactory. I think I can congratulate you on a real discovery.",
        type: "Blurb",
        notes: ["The dust jacket for this edition does not contain any comment by Lewis."]
    },
    {
        id: "3j7wn6",
        title: "Blurb for <i>The Core of the Bible: Arranged from the Authorised King James Version</i>",
        printedIn: "<i>The Core of the Bible: Arranged from the Authorised King James Version,</i> ed. Austin Farrer (New York: Harper and Bros.)",
        issueOrVolume: null,
        pageRange: "back cover",
        year: 1957,
        monthAndDay: null,
        textProvided: "I am more than pleased, I am excited about Austin Farrer’s book. ...This is as brilliant a presentation as we’re likely to see.",
        type: "Blurb",
        notes: ["This blurb was discovered and publicized by Paul Tankard, “Notes on the Bibliography of C.S. Lewis,” <i>Notes & Queries,</i> vol. 263, no. 3 (September 2018), 433.", "An expanded version of the blurb also appears in the publisher’s material at the end of the Fontana paperback edition of <i>Miracles</i> (1960): “I am more than pleased, I am excited, by Austin Farrer’s book. I don’t know that I ever learned so much (from anything of the same sort and on the same scale) as I have done from his introduction. This is a brilliant popularisation [sic] as we are ever likely to see.”"]
    },
    {
        id: "4vbsyx",
        title: "Blurb for E.R. Eddison, <i>The Mezentian Gate</i>",
        printedIn: "E.R. Eddison, <i>The Mezentian Gate</i> (London: Curwen Press, 1958)",
        issueOrVolume: null,
        pageRange: "dust jacket back cover",
        year: 1958,
        monthAndDay: null,
        textProvided: "It is very rarely that a middle-aged man finds an author who gives him, what he knew so often in his teens and twenties, the sense of having opened a new door. One had thought those days were past. Eddison’s heroic romances disproved it. Here was a new literary species, a new rhetoric, a new climate of the imagination. Its effect is not evanescent, for the whole life and strength of a singularly massive and consistent personality lies behind it. Still less, however, is it mere self-expression, appealing only to those whose subjectivity resembles the author’s: admirers of Eddison differ in age and sex and include some (like myself) to whom his world is alien and even sinister. In a word, these books are works, first and foremost, of <i>art</i>. And they are irreplaceable. Nowhere else shall we meet this precise blend of hardness and luxury, of lawless speculation and sharply realised detail, of the cynical and the magnanimous. No author can be said to remind us of Eddison.",
        type: "Blurb",
        notes: ["Reprinted as “A Tribute to E.R. Eddison” in <i>Of This and Other Worlds</i> (1982) and <i>On Stories, and Other Essays on Literature </i> (1982), both edited by Walter Hooper, and <i>Essay Collection & Other Short Pieces</i> (2000), edited by Lesley Walmsley."]
    },
    {
        id: "9zps6r",
        title: "Blurb for Mervyn Peake, <i>Titus Alone</i>",
        printedIn: "Mervyn Peake, <i>Titus Alone,</i> (London: Eyre and Spottiswoode)",
        issueOrVolume: null,
        pageRange: "<a href='https://www.dustjackets.com/pages/books/4090/mervyn-peake/titus-alone' target='_blank' rel='noopener noreferrer' class='link-to-text'></a>dust jacket front and back flaps",
        year: 1959,
        monthAndDay: null,
        textProvided: "In his earlier romances Mr Peake created a new category, the Gormenghastly, and we wonder already how we did without it and why no one defined it before. He now expends the same disquieting power on the experiences of one who has escaped from Gormenghast. But “escaped” now turns out to be the wrong word. The world presented is, with a frightful and fruitful distortion, our own—a world at once triumphant and miserable and having lost its roots, doubtful whether it ever had them save in fantasy, unable to strike new ones, insulted by more than Betjemaniac parodies of the old, both dreading and desiring an impossible return to home; meanwhile, vast, squalid, convulsed with the energies of nightmare. All this, rendered by a prose which sometimes hits you like a mace and sometimes brushes you like a butterfly’s wing, adds up to a work which some will wish to forget as soon as they have read it. They will not succeed.",
        type: "Blurb",
        notes: ["Reprinted in <i>CL</i> 3:1061 note 129 and in Walter Hooper, “A Bibliography of the Writings of C.S. Lewis” in <i>Remembering C.S. Lewis: Recollections of Those Who Knew Him,</i> 3<sup>rd</sup> edition, ed. James T. Como (San Francisco: Ignatius, 2005), 470, item G49."]
    },
    {
        id: "weshn7",
        title: "Blurb for David Bolt, <i>Adam: A Tone Poem</i>",
        printedIn: "David Bolt, <i>Adam: A Tone Poem</i> (New York: John Day Company)",
        issueOrVolume: null,
        pageRange: "dust jacket front flap",
        year: 1961,
        monthAndDay: null,
        textProvided: "I think it splendid. This book does successfully a very difficult thing. To have a sensuous imagination, at once robust and delicate, is much. To embody it in words is more. To do this continually without cloying and suffocating the reader—to combine such richness with such freshness—is more still. But to re-tell the story of Adam as Mr. Bolt has done is most of all. There is no patronage, no parody, no allegorization. The book seems to rise of itself out of prolonged meditation; the author has seen it taking just this shape. We with him, feel it would not have been otherwise. A false step would have been fatal, but the author makes none.",
        type: "Blurb",
        notes: ["A shorter version that omits the second through seventh sentences of the US version was also used for the first UK edition (London: J.M. Dent, 1960), front band around the dust jacket. The shorter UK edition is reprinted in Walter Hooper, “A Bibliography of the Writings of C.S. Lewis” in <i>Remembering C.S. Lewis: Recollections of Those Who Knew Him,</i> 3<sup>rd</sup> edition, ed. James T. Como (San Francisco: Ignatius, 2005), 471, item G52.", "A third, even shorter version was used in an advertisement in <i>The Daily Telegraph and Morning Post</i> (23 September 1960).", "The longest, 10-sentence US version is used on a later UK edition (London: Sidgwick and Jackson, 1979), dust jacket back cover, and is reprinted in Kathryn Lindskoog, <a href='https://www.discovery.org/a/1033/' target='_blank' rel='noopener noreferrer' class='link-to-text'>“A New Discovery: C.S. Lewis Praises Adam,”</a> <i>Lewis Legacy</i>, lxxxvi (Autumn 2000) as well as in Tankard, “Notes on the Bibliography of C.S. Lewis,” <i>Notes & Queries,</i> vol. 263, no. 3 (September 2018), 435."]
    },
    {
        id: "pehwba",
        title: "Blurb for Yvonne Lubbock, <i>Return to Belief</i> (London: Collins, 1961)",
        printedIn: "<i>The Guardian</i>",
        issueOrVolume: null,
        pageRange: "11",
        year: 1961,
        monthAndDay: "28 April",
        textProvided: "Most exciting.",
        type: "Blurb",
        notes: ["The dust jacket for this edition does not contain any comment by Lewis."]
    },
    {
        id: "jwmfea",
        title: "Blurb for Katharine Trevelyan, <i>Fool in Love</i> (London: Victor Gollancz, 1962)",
        printedIn: "<i>The Observer</i>",
        issueOrVolume: null,
        pageRange: "8",
        year: 1962,
        monthAndDay: "1 July",
        textProvided: "As full of pity & terror as Bunyan’s <i>Grace Abounding</i>",
        type: "Blurb",
        notes: ["The dust jacket for this edition does not contain any comment by Lewis."]
    },
    {
        id: "f37agf",
        title: "Blurb for Austin Farrer, <i>Saving Belief</i>",
        printedIn: "Austin Farrer, <i>Saving Belief: A Discussion of Essentials</i> (London: Hodder and Stoughton)",
        issueOrVolume: null,
        pageRange: "half title page",
        year: 1964,
        monthAndDay: null,
        textProvided: "‘It has become customary with theologians to let themselves off a plain answer’ (p. 98). Here plain answers abound. Plain in the sense that no evasions are offered by the writer or permitted to the reader. In another sense, far from plain; almost every answer says more than we realize at the first glance. We have been deluged with theologies in which the most flamboyant pretensions to novelty and daring co-exist with the greatest thinness and flatness of the actual content; Dr. Farrer, remaining patient, modest and orthodox, opens new horizons to us on every other page.",
        type: "Blurb",
        notes: ["According to Paul Tankard, “Notes on the Bibliography of C.S. Lewis,” <i>Notes & Queries,</i> vol. 263, no. 3 (September 2018), 435, Hooper’s 2005 Bibliography “quotes only sixteen words of this blurb: the second half of the last sentence."]
    },
    {
        id: "tczrkh",
        title: "Blurb for Owen Barfield, <i>Orpheus: A Poetic Drama</i>",
        printedIn: "<i>Orpheus: A Poetic Drama</i>, ed. John C. Ulrich, Jr. (West Stockbridge: The Lindisfarne Press,",
        issueOrVolume: null,
        pageRange: "back cover",
        year: 1983,
        monthAndDay: null,
        textProvided: "I await with great interest the public reaction to a work which has influenced me so deeply as Barfield’s ORPHEUS. On the technical side it presents us with a variety almost as rich as that of the Shepherd’s Calendar. I hope this will not be mistaken for virtuosity. The alliterative lines, the trochaics, the couplets, the blank verse and lyrics are in reality so responsive to the different states of being they embody that they serve the same purpose as dramatic orchestration. They mediate a drama which the Orpheus in each of us will understand best if he at first leaves the Eurydice in him free to follow the images and the melodic development. It is a mystery (not a “problem”) drama. It executes in us a re-union of which we always stand in need; never more than at present.",
        type: "Blurb",
        notes: ["Originally printed as a “Note” on the Programme of Owen Barfield’s play <i>Orpheus,</i> produced by the Sheffield Educational Settlement at The Little Theatre, Shipton Street, Sheffield, on 25 September (1948), 8.", "It is also found in <i>CL</i> 2:872-873, where Lewis calls it a “blurb.”"]
    },
    {
        id: "c8xeed",
        title: "Unused blurb for <i>Studies in Words</i> on Cambridge University Press Advance Information Sheet",
        printedIn: "Samantha Rayner and Alison Searle, “C.S. Lewis: Writing and Publishing Literary Criticism with Oxford University Press and Cambridge University Press,” <i>Mémoires du livre / Studies in Book Culture</i>",
        issueOrVolume: "vol. 10, no. 2",
        pageRange: "13 and <a href='https://doi.org/10.7202/1060977ar' target='_blank' rel='noopener noreferrer' class='link-to-text'>online</a>",
        year: 2019,
        monthAndDay: null,
        textProvided: "[{12} Question 6 on the A{dvance} I{nformation} sheet asks about The Book and Its Readers: “Please give a short description of your book in simple non-technical language which will be understood by salesmen and booksellers in all countries–who need to know about it in sufficient detail to direct it towards the right buyers. Please say what it is about, its main purpose, its importance as you see it. {13} Don’t be afraid to state what would be obvious to specialists in your subject.” Lewis’s response is as follows:]<br><br>In how many different senses do you use the words <i>wit</i> or <i>nature</i> (or <i>sense</i> itself)? How many more senses of them have you found in old authors? How did such multiplicity of meanings come about? Do you always know which sense you are using yourself? These are the questions to which this work attempts an answer as regards seven words. They have been selected mainly for the light they throw on the history of thought and sentiment. But it is hoped that the study of them will have for the reader (as it has had for the author) a more than historical interest in increasing his awareness of what we are doing when we talk. It ‘belongs’ on the same shelf as Pearsall Smith’s <i>Four Words,</i> Owen Barfield’s <i>Poetic Diction,</i> and Professor Empson’s <i>Structure of Complex Words</i>.",
        type: "Blurb",
        notes: null
    },
    {
        id: "g2dzna",
        title: "Unused blurb for <i>The Abolition of Man</i> in letter to Roy Niblett (June 14 1943)",
        printedIn: "Michael Ward, <i>After Humanity: A Guide to C.S. Lewis’s The Abolition of Man</i> (Park Ridge: Word on Fire Academic)",
        issueOrVolume: null,
        pageRange: "128",
        year: 2021,
        monthAndDay: null,
        textProvided: "In these lectures Mr. Lewis speaks not as a theologian but as a don. Two foolish schoolbooks become the starting point for a diagnosis of what is implied in much modern educational and social theory. The notion that planners and teachers have a “creative” function is here, perhaps for the first time, subjected to serious examination, and the author discovers in methods to which hundreds of enlightened and conscientious people have lent their authority unawares, <s>an imminent</s> a serious threat to humanity.",
        type: "Blurb",
        notes: null
    }
];
