// Diaries entries — Opera Obscura bibliography (SOURCE OF TRUTH; safe to hand-edit).
// Add new entries anywhere; run the search repo's Scripts/Extraction/OperaObscura/
// normalize_texts.py to re-sort by year + mint a stable id for any new entry.

export const diaries = [
    {
        id: "8efxvr",
        title: "Oxford Diary (15 February 1923)",
        printedIn: "Walter Hooper, preface, C.S. Lewis, <i>Selected Literary Essays,</i> ed. Walter Hooper (Cambridge: Cambridge University Press)",
        issueOrVolume: null,
        pageRange: "xiv",
        year: 1969,
        monthAndDay: null,
        textProvided: "I attempted to get some useful information out of Wyld’s Short History (The Cad) which is full of facts most painfully collected but presented in a very muddled way and extraordinarily difficult to work on.",
        type: "Diary",
        notes: ["Several other quotations from <i>LP</i> in the preface have since been published in <i>AMR.</i>"]
    },
    {
        id: "m74dbn",
        title: "Oxford Diary (9 February 1923)",
        printedIn: "Walter Hooper, “To the Martlets” in <i>C.S. Lewis: Speaker & Teacher,</i> ed. Carolyn Keefe (Grand Rapids: Zondervan)",
        issueOrVolume: null,
        pageRange: "47-50",
        year: 1971,
        monthAndDay: null,
        textProvided: "[In <i>C.S. Lewis: Speaker & Teacher, </i>50:]<br><br>I said this was certainly not what I meant by art: in fact it stood to art as Narcissus to Eros.<br><br>[In <i>AMR:</i>]<br><br>I said this was certainly not what I meant by art: in fact it stood to art as ———.",
        type: "Diary",
        notes: ["This passage is entirely reproduced in <i>AMR,</i> but with an interesting discrepancy. The last three words in this entry, as printed in <i>C.S. Lewis: Speaker & Teacher,</i> are: “Narcissus to Eros.” However, in <i>AMR</i> and the diary manuscript, there is a blank line, as follows: “I said this was certainly not what I meant by art: in fact it stood to art as ———.” The words “Narcissus to Eros” are probably an editorial insertion."]
    },
    {
        id: "xbarm4",
        title: "Little Lea Diary excerpts",
        printedIn: "Roger Lancelyn Green and Walter Hooper, <i>C.S. Lewis: A Biography</i> (London: Collins; New York: Harcourt Brace Jovanovich)",
        issueOrVolume: null,
        pageRange: "24",
        year: 1974,
        monthAndDay: null,
        textProvided: "[Warren departed to boarding-school in England, while Clive was taught at Little Lea by a governess called Miss Harper:]<br><br>She is fairly nice <i>for</i> a governess, but all of them are the same <br><br>[he confided to his first diary at the end of 1907, in which he describes himself as]<br><br>like most boys of nine, and I am like Papy, bad temper, thick lips, thin and generally wearing a jersey.<br><br>[Other diary scraps describe the rest of the household: his grandfather, Richard Lewis:]<br><br>who lives in a little room of his own upstairs<br><br>[Maude the housemaid and Martha the cook; several pets:]<br><br>a dog called Tim, a black and white mouse called Tommy, and lastly a canary called Peter.<br><br>[The entry for Thursday, 5 March 1908 is typical-except for the unexpected item with which it concludes:]<br><br>I rise. The lawn is white with frost. I have breakfast. Get my coat and cap and see Papy off. Miss Harper comes. Lessons. <br><br>[The next entry translates the opening sentence of <i>De Bello Gallico.</i>] <br><br>Dinner. I am carpentring at a sword. I read “Paradise Lost”, reflections there-on.",
        type: "Diary",
        notes: ["The entry for 5 March 1908 (<i>LP</i> 3:102) is reprinted in George Sayer, <i>Jack: C.S. Lewis and His Times</i> (London: Macmillan; San Francisco: Harper & Row, 1988), 20-21. Scan available here. Reprinted in 2<sup>nd</sup> edition, retitled <i>Jack: A Life of C.S. Lewis</i> (Wheaton, IL: Crossway Books, 1994), 51. Text as follows: “I read <i>Paradise Lost,</i> reflections thereon.”"]
    },
    {
        id: "wcm9r6",
        title: "Wynyard Diary (November 1909)",
        printedIn: "Roger Lancelyn Green and Walter Hooper, <i>C.S. Lewis: A Biography</i> (London: Collins; New York: Harcourt Brace Jovanovich)",
        issueOrVolume: null,
        pageRange: "27",
        year: 1974,
        monthAndDay: null,
        textProvided: "[He was also attempting another diary, or]<br><br>Autobiography<br><br>[as he calls it, of his experiences among the]<br><br>five boarders at this ridiculous ‘select academy for young gentlemen’—Squiffy [Field], Bowser, Mears, Jeyes and me …Oldy and his son Wyn are the only masters here, and Wyn can’t teach for nuts either.",
        type: "Diary",
        notes: ["Lewis names the “five boarders” at his school (later quoted more fully in Hooper’s 1982 article).", "This page also contains the only printing of the following sentence from the Wynyard diary about the two teachers at Wynyard: “Oldy and his son Wyn are the only masters here, and Wyn can’t teach for nuts either.”"]
    },
    {
        id: "x9mhh4",
        title: "Little Lea Diary excerpts",
        printedIn: "Humphrey Carpenter, <i>The Inklings: C.S. Lewis, J.R.R. Tolkien, Charles Williams, and Their Friends</i> (London: Allen & Unwin)",
        issueOrVolume: null,
        pageRange: "3, 4",
        year: 1978,
        monthAndDay: null,
        textProvided: "[3]<br><br>My Life during the Exmas Holydays of 1907, by Jacks or Clive Lewis. Author of “Building of the promenad”, “Toyland”, “Living races of mouse-land” etc. I begin my life after my 9th birthday. On which I got a book from Papy and a post card album from Mamy. Warnie (my brother) was coming home and I was looking forward to him and the Xmas holydays.<br><br>[4]<br><br>Mamy is like most middle-aged ladys, stout, brown hair, spectaciles, kniting her cheif industry etc. etc. Papy of course is the master of the house, and a man in whom you can see strong Lewis features, bad temper, very sensible, nice when not in a temper. I am like most boys of 9 and I am like Papy, bad temper, thick lips, thin, and generaly weraing a jersey.",
        type: "Diary",
        notes: ["Quotes the first sentences on page 3 (not quoted in Hooper’s 1974 biography). On page 4 describes his mother, father, and himself in greater detail than the excerpts in the 1974 biography, and retains the original spelling."]
    },
    {
        id: "pta6xu",
        title: "Oxford Diary (21 February 1923)",
        printedIn: "Humphrey Carpenter, <i>The Inklings: C.S. Lewis, J.R.R. Tolkien, Charles Williams, and Their Friends,</i> (London: Allen & Unwin)",
        issueOrVolume: null,
        pageRange: "15",
        year: 1978,
        monthAndDay: null,
        textProvided: "We were neither of us in really good dialectical form.",
        type: "Diary",
        notes: null
    },
    {
        id: "nq57u2",
        title: "Oxford Diary (26 August 1922)",
        printedIn: "Roger Lancelyn Green, “In the Evening” in <i>C.S. Lewis at the Breakfast Table and Other Reminiscences,</i> ed. James T. Como (New York: Macmillan)",
        issueOrVolume: null,
        pageRange: "213",
        year: 1979,
        monthAndDay: null,
        textProvided: "The next thing I remember was coming back from Malvern. On the way I met a big cart driven by a girl who had no clothes on. She had very light brown hair: but dark skin, pink-brown like sand. I smiled at her in the confidential way one might smile at a girl when you’d seen a hole in her stocking, and she smiled back in just the same way, as much as to say, “Yes, I know. Isn’t it a scream!” Then I went back to Malvern and woke up—having seen the girl again, this time in the distance beyond the river, with other people in the cart.",
        type: "Diary",
        notes: null
    },
    {
        id: "gkzm9y",
        title: "Wynyard Diary (November 1909)",
        printedIn: "Walter Hooper, “C.S. Lewis in Hertfordshire (2): Wynyard School’s Tormenter”, <i>Hertfordshire Countryside</i>",
        issueOrVolume: "vol. 37",
        pageRange: "35",
        year: 1982,
        monthAndDay: null,
        textProvided: "It was on a black November morning, in the year of grace 1909, that I, Clive Staples Lewis, pulled myself reluctantly from my bed, in an uncomfortable corner of the dormitory, at the abominably early hour of 7.30 a.m. Mindful, however, that a halfpenny fine awaited me if I were late, I began to wash in icy water with all reasonable despatch …We were obliged to go to St. Johns; a church which wanted to be Roman Catholic, but was afraid to say so. A kind of church abhorred by respectful Irish protestants. Here Wyn Capron, the son of our head master, preached a sermon, better than his usual ones. In this abominable place, of Romish hypocrites and English liars, the people cross themselves, bow to the Lord’s table (which they have the vanity to call an “altar”), and pray to the Virgin …The boarders at this ridiculous little “select academy for young gentlemen” are five in number, Squiffy, Mears, Bowser, Jeyes and me […] Boivie is a Swede, and a good old Northerner, who like me loaths anything that savours of the South of England. Nice as Boivie is, my great chum is Bowser. He comes from Northumberland and is staunchly Northern, he (and this makes me like him more) is very badly treated by our Southern master Mr. Capron, better known to us as “Oldy” …It is funny, as you go North the people get nicer, as you go South they get nastier, thus Bowser from Cumberland, is the nicest boy here, Jeyes from Northampton is the next nicest, Mears from Chiswick is a middling boy, and Squiffy from Worthing in Sussex is the nastiest boy here …<br><br>…No one got caned today.",
        type: "Diary",
        notes: ["Includes the morning routine previously published in Walter Hooper, “C.S. Lewis”, <i>The Franciscan,</i> vol. IX, no. 4 (September 1967), 163. The first two sentences of the diary are quoted, chronicling Lewis’s morning routine. Text as follows: “It was on a bleak November morning, in the year of grace 1901 [must be misprint for 1909–this would make Lewis only 3 years old], that I, Clive Staples Lewis, pulled myself reluctantly from my bed, in an uncomfortable corner of the dormitory, at the abominably early hour of 7.30 A.M. Mindful, however, that a halfpenny fine awaited me if I were late, I began to wash in icy water with all reasonable despatch.”", "Also includes the anti-Catholicism passage previously published in Walter Hooper, <i>Through Joy and Beyond: A Pictorial Biography of C.S. Lewis</i> (New York: Macmillan, 1982), 19. Text as follows: “We were obliged to go to St John’s; a church which wanted to be Roman Catholic, but was afraid to say so. A kind of church abhorred by respectful Irish protestants. Here Wyn Capron, the son of our headmaster, preached a sermon, better than his usual ones. In this abominable place, of Romish hypocrites, and English liars, the people cross themselves, bow to the Lord’s Table (which they have the vanity to call an altar), and pray to the Virgin.”", "The same anti-Catholicism passage, though slightly less of it, had also been published in Humphrey Carpenter, <i>The Inklings: C.S. Lewis, J.R.R. Tolkien, Charles Williams, and their friends</i> (London: Allen & Unwin, 1978), 50. There are 3 editorial differences: (1) different punctuation, (2) the insertion of the explanatory “(Watford)” after “St John’s,” and (3) the silent omission of the sentence: “Here Wyn Capron, the son of our headmaster, preached a sermon, better than his usual ones.” Text as follows: “We were obliged to go to St John’s (Watford), a church which wanted to be Roman Catholic, but was afraid to say so. A kind of church abhorred by respectful Irish Protestants. In this abominable place of Romish hypocrites and English liars, the people cross themselves, bow to the Lord’s Table (which they have the vanity to call an altar), and pray to the Virgin.”"]
    },
    {
        id: "x6q4we",
        title: "Bookham Diary (19 July 1915 [<i>LP</i> 4:328])",
        printedIn: "Walter Hooper, preface to <i>Spirits in Bondage,</i> ed. Walter Hooper (New York: Harcourt Brace Jovanovich)",
        issueOrVolume: null,
        pageRange: "xxi",
        year: 1984,
        monthAndDay: null,
        textProvided: "Had ghastly dreams about the front and getting wounded last night.",
        type: "Diary",
        notes: null
    },
    {
        id: "66dhnj",
        title: "Oxford Diary (3 June 1926)",
        printedIn: "Peter J. Schakel, <i>Reason and Imagination in C.S. Lewis: A Study of</i> Till We Have Faces (Grand Rapids: Eerdmans)",
        issueOrVolume: null,
        pageRange: "44",
        year: 1984,
        monthAndDay: null,
        textProvided: "a curious dream in the night.",
        type: "Diary",
        notes: ["Schakel groups four entries from the Oxford Diary on Lewis’s dreams. The first three (from 4 July 1922, 12 September 1923, and 22 February 1924) are in <i>AMR.</i> The final one, however, is not."]
    },
    {
        id: "y3kxj4",
        title: "Little Lea Diary excerpts",
        printedIn: "Walter Hooper’s introduction to <i>Boxen: The Imaginary World of the Young C.S. Lewis</i> (London: Collins)",
        issueOrVolume: null,
        pageRange: "12",
        year: 1985,
        monthAndDay: null,
        textProvided: "[During the Christmas holidays of 1907 nine-year-old Jack began the first of his diaries. Or, more accurately, his first autobiography as it bears the title]<br><br><i>My Life</i><br><br>[Jack intended that the <i>Life</i> should be read by all in the house and it is dedicated]<br><br>To Miss Maude Scott <br><br>[That was to prove very embarrassing because in the first paragraph he writes]<br><br>I have a lot of enymays, however there are only 2 in this house they are called Maude and Mat, Maude is far worse than Mat, but she thinks she is a saint […] I HATE Maude. <br><br>[He goes on to say:]<br><br>Papy of course is the master of the house, and a man in whom you can see strong Lewis features, bad temper, very sensible, nice wen not in a temper. Mamy is like most middle-aged ladys, stout, brown hair, spectaciles, kniting her cheif industry etc. etc. I am like most boys of 9 and I am like Papy, bad temper, thick lips, thin and generally weraing a jersey. <br><br>[After describing the pets (a mouse, a canary and a dog) he mentions his paternal grandfather:]<br><br>I have left out an important member of the family namly my grand-father, who lives in a little room of his own up-stairs he is a nice old man in some ways but he pitys him-self rather much, however all old people do that.<br><br>[So great was his affection for Warnie that there is a section of the Life entitled]<br><br>Part IV.  How Warnie came home.<br><br>[As, however, Warnie had not yet arrived from Wynyard, Jack went on to write:]<br><br>I am still looking forward to Wanrie’s homecoming which is always a great event in our house. You see I had to wait for something to happen before I could write about it, and I put down “Part IV” “How Warnie came home” with out thinking…therefore I shall have to fill up “Part IV” with other things. I have yet left out another important person who plays a large part in “my life”, namely “Miss Harper” who is my governess. She is fairly nice FOR a governess, but all of them are the same. Miss Harper has fair hair, blue eyes, and rather sharp features, she generally wears a green blouse and a dress of the same hue.<br><br>[Included in the Life was a drawing of Miss Harper with a ‘balloon’ coming down from her lips which contained the words]<br><br>Don’t say can’t to me, Jacksie.<br><br>[Notebook II overlaps with number I and Jack scribbled in it:]<br><br>I often wish that I was leading a more use-ful life.",
        type: "Diary",
        notes: ["Hooper’s introduction was reprinted as “The History of Boxen” in <i>Boxen: Childhood Chronicles Before Narnia</i> (London: HarperCollins, 2008), and this entry can be found on 233-234."]
    },
    {
        id: "qghpu9",
        title: "Little Lea Diary excerpts",
        printedIn: "C.S. Lewis, <i>Letters to Children,</i> eds. Lyle W. Dorsett and Marjorie L. Mead (New York: Macmillan)",
        issueOrVolume: null,
        pageRange: "8",
        year: 1985,
        monthAndDay: null,
        textProvided: "Papy is of course the master of the house, and a man in whom you can see strong Lewis features, bad temper, very sensible, nice wen not in a temper. Mamy is like most middle aged ladys, stout, brown hair, spectaciles, kniting her cheif industry. I am like most boys of 8 and I am like Papy, bad temper, thick lips, thin, and generaly weraing a jersey. ...Hoora! Warnie comes home this morning. I am lying in bed waiting for him and thinking about him, and before I know where I am I hear his boots pounding on the stairs, he comes into the room, we shake hands and begin to talk…",
        type: "Diary",
        notes: null
    },
    {
        id: "e6yvfh",
        title: "Cherbourg Diary (15 March 1911 [<i>LP</i> 3:229])",
        printedIn: "George Sayer, <i>Jack: C.S. Lewis and His Times</i> (London: Macmillan; San Francisco: Harper & Row)",
        issueOrVolume: null,
        pageRange: "30",
        year: 1988,
        monthAndDay: null,
        textProvided: "[At Cherbourg he was soon in trouble, having to do (according to his diary)]<br><br>hundreds of impots<br><br>[that is, impositions, tasks assigned to him for breaking school rules, misbehaving in the classroom, and not preparing his work. This diary, like all the other diaries he began, was kept for only a short time. It contains the thoughts of a typical schoolboy: Masters are]<br><br>rotten<br><br>[when the punish one for misbehaving…[Miss Cowie] was the school’s exceptionally kind and efficient matron. She recognized at once that {67} Jack was almost an orphan and mothered him with a special degree of love and care to which he responded gratefully.]<br><br>They all love her<br><br>[he wrote]<br><br>I, an orphan, especially.",
        type: "Diary",
        notes: ["Reprinted in 2<sup>nd</sup> edition, retitled <i>Jack: A Life of C.S. Lewis</i> (Wheaton, IL: Crossway Books, 1994), 66-67.", "The text on Miss Cowie (“They all love her…I, an orphan, especially” may be a misquotation of <i>SBJ</i> ch. 4: “We all loved her; I, the orphan, especially.” Or, it’s possible that Lewis used his Cherbourg diary as a source for <i>SBJ</i> and lightly reworked it. Either way Sayer does not footnote those quotations, so I am not sure of their provenance."]
    },
    {
        id: "ywryup",
        title: "Little Lea Diary (23 February 1908 [<i>LP</i> 3:301]), a bibliography of his works at 10 years old",
        printedIn: "George Sayer, <i>Jack: C.S. Lewis and His Times</i> (London: Macmillan; San Francisco: Harper & Row)",
        issueOrVolume: null,
        pageRange: "21",
        year: 1988,
        monthAndDay: null,
        textProvided: "list of my books<br><br>Building of the Promenade (a tale)<br>Man Against Man (a novel)<br>Town (an essay)<br>Relief of Murry (a history)<br>Bunny (a paper)<br>Home Rule (an essay)<br>My Life (a journal)",
        type: "Diary",
        notes: ["Only partially reprinted in 2<sup>nd</sup> edition, retitled <i>Jack: A Life of C.S. Lewis</i> (Wheaton, IL: Crossway Books, 1994), 51."]
    },
    {
        id: "4ejd6n",
        title: "Little Lea Diary (Christmas 1907 [<i>LP</i> 3:89])",
        printedIn: "George Sayer, <i>Jack: C.S. Lewis and His Times</i> (London: Macmillan; San Francisco: Harper & Row)",
        issueOrVolume: null,
        pageRange: "20",
        year: 1988,
        monthAndDay: null,
        textProvided: "[The worst thing about Grandfather Lewis was that he is dirty:] <br><br>allways spitting and smoking ugh!",
        type: "Diary",
        notes: ["Reprints everything in Walter Hooper’s introduction to <i>Boxen: The Imaginary World of the Young C.S. Lewis</i> (London: Collins, 1985) with the exception of a new bit on Grandfather Lewis.", "Reprinted in 2<sup>nd</sup> edition, retitled <i>Jack: A Life of C.S. Lewis</i> (Wheaton, IL: Crossway Books, 1994), 50-51."]
    },
    {
        id: "xn2qrb",
        title: "Notebook entry (28 April 1917 [<i>LP</i> 5:204])",
        printedIn: "George Sayer, <i>Jack: C.S. Lewis and His Times</i> (London: Macmillan; San Francisco: Harper & Row)",
        issueOrVolume: null,
        pageRange: "64",
        year: 1988,
        monthAndDay: null,
        textProvided: "Matriculated. College Library. Entered name in Coll. books.",
        type: "Diary",
        notes: ["Reprinted in 2<sup>nd</sup> edition, retitled <i>Jack: A Life of C.S. Lewis</i> (Wheaton, IL: Crossway Books, 1994), 118."]
    },
    {
        id: "4r2dnk",
        title: "Oxford Diary (17 February 1923)",
        printedIn: "George Sayer, <i>Jack: C.S. Lewis and His Times</i> (London: Macmillan; San Francisco: Harper & Row)",
        issueOrVolume: null,
        pageRange: "99",
        year: 1988,
        monthAndDay: null,
        textProvided: "[In the diary of the period he described Dryden as]<br><br>an intolerable worm",
        type: "Diary",
        notes: ["Reprinted in 2<sup>nd</sup> edition, retitled <i>Jack: A Life of C.S. Lewis</i> (Wheaton, IL: Crossway Books, 1994), 171."]
    },
    {
        id: "rqx9cu",
        title: "Little Lea Diary excerpts",
        printedIn: "A.N. Wilson, <i>C.S. Lewis: A Biography</i> (New York: W.W. Norton)",
        issueOrVolume: null,
        pageRange: "17-18",
        year: 1990,
        monthAndDay: null,
        textProvided: "My life during the Xmas holidsas [sic] of 1907 by Jacks or Clive Lewis author of “Building of the Promanad”, “Toyland”, “Living races of Mouse-Land” etc. Dedicated to Miss Maude Scott. I begin my life after my 9th birthday, on which I got a book from Papy and a post-card album from Mamy. I have a lot of enymays...",
        type: "Diary",
        notes: ["Includes passages previously printed describing the appearances of his mother, father, and himself, as well as the anecdote about his excitement hearing Warnie come home. The only new bit is the full title and opening sentence of “My life.”"]
    },
    {
        id: "e3f344",
        title: "Oxford Diary (25 May 1923)",
        printedIn: "A.N. Wilson, <i>C.S. Lewis: A Biography</i> (New York: W.W. Norton)",
        issueOrVolume: null,
        pageRange: "69",
        year: 1990,
        monthAndDay: null,
        textProvided: "We each had a man wrapped in sacking and helmeted with a biscuit tin, and we are throwing them up in the air to kill them with the fall. When that failed it became one man whom we succeeded in murdering (I am not sure how. I think by drumming his head on the pavement) and the rest of the dream consists of fearful anxiety lest we should be discovered.",
        type: "Diary",
        notes: null
    },
    {
        id: "q6hvg4",
        title: "Little Lea Diary excerpts (<i>LP</i> 3:88-92)",
        printedIn: "Walter Hooper, <i>C.S. Lewis: A Companion & Guide</i> (New York: HarperCollins)",
        issueOrVolume: null,
        pageRange: "6 and 696",
        year: 1996,
        monthAndDay: null,
        textProvided: "[{6}]<br><br>Hoora!! Warnie comes home this morning. I am lying in bed waiting for him and thinking of him, before I know where I am I hear his boots pounding on the stairs, he comes into the room, we shake hands and begin to talk...Well I was glad to have him but of course we had our rows afterwards…<br><br>[{696} As Christmas draws near we learn how Warnie comes home from school, of the various Lewis and Hamilton relations who drop in, how]<br><br>Mamy stoned raisins for the Xmas pudding<br><br>[of how Jack and Warnie take to]<br><br>rushing about the house<br><br>[and of the play which Jack is writing to perform for the family on Christmas Day. The document ends with the words:] <br><br>The old year out and the new year in ",
        type: "Diary",
        notes: ["TReprints old material but also includes new content not published before, chiefly (a) differences of punctuation and some word choices in how Warnie came home; (b) a new sentence on how Warnie came home; (c) actual details about Christmas that year; (d) the closing sentence of the diary.","This passage in the <i>Companion & Guide</i> was later reproduced in part by Zaleski and Zaleski, <i>The Fellowship: The Literary Lives of the Inklings</i> (New York, Farrar, Strauss and Giroux, 2015), 40."]
    },
    {
        id: "bps6x5",
        title: "Cherbourg Diary (March 1911)",
        printedIn: "Harry Lee Poe, <i>Becoming C.S. Lewis: A Biography of Young Jack Lewis (1898-1918)</i> (Wheaton, IL: Crossway Books)",
        issueOrVolume: null,
        pageRange: "58",
        year: 2019,
        monthAndDay: null,
        textProvided: "[During his first term at Cherbourg, Jack attempted to keep a diary once again, beginning on March 11, 1911, but he kept it up only until March 19. His comments reflect a marked difference between playing games at Wynyard and the tone of sports at Cherbourg. They were no longer boys playing. They were chaps training. His most common description?]<br><br>Rotten<br><br>[He was rotten at sports training. He was rotten at the long jump (2 feet, 11 inches). He was rotten at hockey. In boxing, however, he was not rotten. He]<br><br>got a tremendous knocking about",
        type: "Diary",
        notes: null
    },
    {
        id: "sxu3e6",
        title: "Wynyard Diary (November 1909)",
        printedIn: "Harry Lee Poe, <i>Becoming C.S. Lewis: A Biography of Young Jack Lewis (1898-1918)</i> (Wheaton, IL: Crossway Books)",
        issueOrVolume: null,
        pageRange: "44, 45 and 280 note 106",
        year: 2019,
        monthAndDay: null,
        textProvided: "[Jacks named Bowser as his]<br><br>great chum<br><br>[largely because Capron mistreated him for being from northern England, calling him a]<br><br>great north country lout.<br><br>[Field, on the other hand, had all of the principal characteristics of the English, in Jack’s opinion:]<br><br>selfishness, cruelty, pride, and underhand dealing.<br><br>[{45} In journal entries from his time at Wynyard, it is obvious that Jacks thought games could be fun. In one exciting game of rounders in which Jacks chose players, his team almost won, except]<br><br>for a howling catch by Boivie, and another by Mears, and an idiotically risky run by me.<br><br>[{280 note 106} See also 3:205, where Jacks describes playing games over a period of several days during which he found bowlers]<br><br>good fun",
        type: "Diary",
        notes: ["Also reprints most of the text on his anti-Catholic sentiment about St John’s in Watford and recounts in indirect discourse his theory about how boys become nicer the farther north you go."]
    },
    {
        id: "xmmpc9",
        title: "Oxford Diary (10 May 1922 [<i>LP</i> 8:135])",
        printedIn: "Arend Smilde, “Why C.S. Lewis did not become a philosopher: Biographical Introduction” in “C.S. Lewis: Tutor and Lecturer in Philosophy: Philosophical Notes (1924),” eds. Norbert Feinendegen and Arend Smilde, <i>Inklings Studies Supplements</i>",
        issueOrVolume: "no. 2",
        pageRange: "71",
        year: 2021,
        monthAndDay: null,
        textProvided: "[Lewis had been working on a prose version of his long poem “Foster” (which does not survive). That prose essay was  intended as an answer to Bertrand Russel’s “A Free Man’s Worship,” and is mentioned as a finished work in a somewhat enigmatic and partly unpublished diary passage of 10 May 1922:]<br><br>I was thinking seriously of how I could face the prospect of having to give up poetry, if it came to that. I was surprised to discover how many hidden assuptions [sic] about contemporary recognition etc underlay the view I had taken in Foster wh. is really that of ‘Sache’(?)—so there is more to be said for Hegel than I once thought. <br><br>[{71 note 108} The first sentence is also in <i>AMR,</i> 32. The question mark in parentheses is original to the ‘Lewis Papers’, perhaps added by Warnie Lewis while typing the text from the manuscript diary.]",
        type: "Diary",
        notes: null
    },
    {
        id: "uy9wwk",
        title: "Oxford Diary (12 May 1924 [<i>LP</i> 8:228])",
        printedIn: "Arend Smilde, “Why C.S. Lewis did not become a philosopher: Biographical Introduction” in “C.S. Lewis: Tutor and Lecturer in Philosophy: Philosophical Notes (1924),” eds. Norbert Feinendegen and Arend Smilde, <i>Inklings Studies Supplements</i>",
        issueOrVolume: "no. 2",
        pageRange: "75",
        year: 2021,
        monthAndDay: null,
        textProvided: "Worked partly on Locke and partly on a scheme for my lectures in the morning.",
        type: "Diary",
        notes: ["The same text is partially quoted on page 5 note 11.", "Perhaps Lewis is referring to his notes for his lectures on “The Good” or “Moral Good,” or to some larger or similar or related document."]
    },
    {
        id: "8eeaux",
        title: "Oxford Diary (14 June 1922 [<i>LP</i> 7:157])",
        printedIn: "Arend Smilde, “Why C.S. Lewis did not become a philosopher: Biographical Introduction” in “C.S. Lewis: Tutor and Lecturer in Philosophy: Philosophical Notes (1924),” eds. Norbert Feinendegen and Arend Smilde, <i>Inklings Studies Supplements</i>",
        issueOrVolume: "no. 2",
        pageRange: "48",
        year: 2021,
        monthAndDay: null,
        textProvided: "Blunt told me I need not be afraid of Ewing’s competition for the Magdalen Fellowship on the ground of his being a Demy, as it would be decided entirely on your papers.<br><br>[{48 note 26} H.P. Blunt was another Greats man; a ‘Demy’ is a scholarship for Magdalen College, Oxford.]",
        type: "Diary",
        notes: null
    },
    {
        id: "g7nvpc",
        title: "Oxford Diary (15 March 1923 [<i>LP</i> 8:91])",
        printedIn: "Arend Smilde, “Why C.S. Lewis did not become a philosopher: Biographical Introduction” in “C.S. Lewis: Tutor and Lecturer in Philosophy: Philosophical Notes (1924),” eds. Norbert Feinendegen and Arend Smilde, <i>Inklings Studies Supplements</i>",
        issueOrVolume: "no. 2",
        pageRange: "56",
        year: 2021,
        monthAndDay: null,
        textProvided: "[On 15 March 1923 Lewis noted that he had recently asked his old philosophy tutor Carritt]<br><br>whether there would be any use applying for the Newcastle job wh. D had found in <i>The Times.</i> He confirmed my own opinion that they wanted an experienced man and it wd. be quite out of the question for me: mentioning at the same time a philosophical vacancy at Nottingham wh. I must see to.",
        type: "Diary",
        notes: null
    },
    {
        id: "2kcr9k",
        title: "Oxford Diary (19 June 1924 [<i>LP</i> 8:245])",
        printedIn: "Arend Smilde, “Why C.S. Lewis did not become a philosopher: Biographical Introduction” in “C.S. Lewis: Tutor and Lecturer in Philosophy: Philosophical Notes (1924),” eds. Norbert Feinendegen and Arend Smilde, <i>Inklings Studies Supplements</i>",
        issueOrVolume: "no. 2",
        pageRange: "73-74",
        year: 2021,
        monthAndDay: null,
        textProvided: "[On 19 June Lewis noted that one student, Ziman]<br><br>is taking P.P.E. next term and will be coming to me for ordinary tuition: he wants however to take Kant as his special subject. He knew from what I had often said to him before that I was not a Kantian, but asked if I would be “compos Kantis” next term. I said that I should follow Carritt’s example in handing Kantians over to Ewing. Ziman however showed a strong disinclination to that solution and wanted to go to Paton: but this could not be arranged while Carritt was ill and so we had to let the matter stand.<br><br>[Moreover, that same morning Lewis had been invited to]<br><br>take Carlyle’s English pupils next term when Carlyle is away",
        type: "Diary",
        notes: null
    },
    {
        id: "g6z63m",
        title: "Oxford Diary (19 October 1923 [<i>LP</i> 8:160])",
        printedIn: "Arend Smilde, “Why C.S. Lewis did not become a philosopher: Biographical Introduction” in “C.S. Lewis: Tutor and Lecturer in Philosophy: Philosophical Notes (1924),” eds. Norbert Feinendegen and Arend Smilde, <i>Inklings Studies Supplements</i>",
        issueOrVolume: "no. 2",
        pageRange: "63",
        year: 2021,
        monthAndDay: null,
        textProvided: "[On the porch of University College Lewis met]<br><br>...Curtis, Rink and Ziman. The latter asked me to read a paper to the Philosophical Society next week, which I promised to do, meaning to use my old Magdalen dissertation. After walking home I looked over it till lunch time to see what could be cut out, but I think it is not much too long.",
        type: "Diary",
        notes: null
    },
    {
        id: "93g4jg",
        title: "Oxford Diary (21 August 1922 [<i>LP</i> 7:206])",
        printedIn: "Arend Smilde, “Why C.S. Lewis did not become a philosopher: Biographical Introduction” in “C.S. Lewis: Tutor and Lecturer in Philosophy: Philosophical Notes (1924),” eds. Norbert Feinendegen and Arend Smilde, <i>Inklings Studies Supplements</i>",
        issueOrVolume: "no. 2",
        pageRange: "53",
        year: 2021,
        monthAndDay: null,
        textProvided: "After lunch I sat in my own room and worked on my dissertation with immense enjoyment",
        type: "Diary",
        notes: null
    },
    {
        id: "fsq98x",
        title: "Oxford Diary (21 May 1924 [<i>LP</i> 8:230])",
        printedIn: "Arend Smilde, “Why C.S. Lewis did not become a philosopher: Biographical Introduction” in “C.S. Lewis: Tutor and Lecturer in Philosophy: Philosophical Notes (1924),” eds. Norbert Feinendegen and Arend Smilde, <i>Inklings Studies Supplements</i>",
        issueOrVolume: "no. 2",
        pageRange: "63 note 79",
        year: 2021,
        monthAndDay: null,
        textProvided: "Worked in the morning preparing the subject of Bolshevism for Sandeman",
        type: "Diary",
        notes: null
    },
    {
        id: "sv3axg",
        title: "Oxford Diary (3 June 1924 [<i>LP</i> 8:236])",
        printedIn: "Norbert Feinendegen, “The Refutation of Empiricism: Philosophical Introduction” in “C.S. Lewis: Tutor and Lecturer in Philosophy: Philosophical Notes (1924),” eds. Norbert Feinendegen and Arend Smilde, <i>Inklings Studies Supplements</i>",
        issueOrVolume: "no. 2",
        pageRange: "13 note 52",
        year: 2021,
        monthAndDay: null,
        textProvided: "[On 3 June 1924 Lewis noted in an unpublished part of his diary that Locke’s <i>Essay</i> is]<br><br>a book as “thin sown of aught of profit or delight” as any I have ever read<br><br>[The quotation is from Milton, <i>Paradise Regained,</i> Book IV, line 345; the transcription of the diary actually reads ‘strewn’ instead of ‘sown’, which may have been Lewis’ or the transcriber’s error.]",
        type: "Diary",
        notes: null
    },
    {
        id: "sfrwwk",
        title: "Oxford Diary (30 May 1924 [<i>LP</i> 8:235])",
        printedIn: "Arend Smilde, “Why C.S. Lewis did not become a philosopher: Biographical Introduction” in “C.S. Lewis: Tutor and Lecturer in Philosophy: Philosophical Notes (1924),” eds. Norbert Feinendegen and Arend Smilde, <i>Inklings Studies Supplements</i>",
        issueOrVolume: "no. 2",
        pageRange: "63 note 79 and 69",
        year: 2021,
        monthAndDay: null,
        textProvided: "[{63 note 29} Lewis purchased]<br><br>Mill’s Liberty etc. in the Everyman edition wh. I want for Sandeman<br><br>[{69} One of the last references to the “new version” of Lewis’s “Hegemony of Moral Value” paper:]<br><br>…started to work on a new ending for my paper on mind—the part on Obligation.",
        type: "Diary",
        notes: null
    },
    {
        id: "r9eqw9",
        title: "Oxford Diary (31 May 1924 [<i>LP</i> 8:235])",
        printedIn: "Arend Smilde, “Why C.S. Lewis did not become a philosopher: Biographical Introduction” in “C.S. Lewis: Tutor and Lecturer in Philosophy: Philosophical Notes (1924),” eds. Norbert Feinendegen and Arend Smilde, <i>Inklings Studies Supplements</i>",
        issueOrVolume: "no. 2",
        pageRange: "69",
        year: 2021,
        monthAndDay: null,
        textProvided: "[One of the last references to the “new version” of Lewis’s “Hegemony of Moral Value” paper:]<br><br>…Worked on my paper in the morning very hard and fairly successfully.",
        type: "Diary",
        notes: null
    },
    {
        id: "2xtv3a",
        title: "Oxford Diary (6 March 1924 [<i>LP</i> 8:192])",
        printedIn: "Arend Smilde, “Why C.S. Lewis did not become a philosopher: Biographical Introduction” in “C.S. Lewis: Tutor and Lecturer in Philosophy: Philosophical Notes (1924),” eds. Norbert Feinendegen and Arend Smilde, <i>Inklings Studies Supplements</i>",
        issueOrVolume: "no. 2",
        pageRange: "75",
        year: 2021,
        monthAndDay: null,
        textProvided: "I came away very heartened. Walked with Price as far as Magdalen…",
        type: "Diary",
        notes: ["Earlier parts of this entry had already been published in <i>AMR,</i> 298-299."]
    },
    {
        id: "ev8hxm",
        title: "Oxford Diary (7 June 1924)",
        printedIn: "Arend Smilde, “Why C.S. Lewis did not become a philosopher: Biographical Introduction” in “C.S. Lewis: Tutor and Lecturer in Philosophy: Philosophical Notes (1924),” eds. Norbert Feinendegen and Arend Smilde, <i>Inklings Studies Supplements</i>",
        issueOrVolume: "no. 2",
        pageRange: "69",
        year: 2021,
        monthAndDay: null,
        textProvided: "worked on my paper in the morning",
        type: "Diary",
        notes: ["Identical to 9 June 1924 entry.", "Possibly a reference to his “Hegemony of Moral Value” paper."]
    },
    {
        id: "cb8gxq",
        title: "Oxford Diary (8 March 1924 [<i>LP</i> 8:197]) correction to <i>All My Road Before Me</i>",
        printedIn: "Arend Smilde, “Why C.S. Lewis did not become a philosopher: Biographical Introduction” in “C.S. Lewis: Tutor and Lecturer in Philosophy: Philosophical Notes (1924),” eds. Norbert Feinendegen and Arend Smilde, <i>Inklings Studies Supplements</i>",
        issueOrVolume: "no. 2",
        pageRange: "67",
        year: 2021,
        monthAndDay: null,
        textProvided: "[Lewis describes Samuel Alexander’s]<br><br>fruitful antithesis between enjoyment and contemplation<br><br>[But <i>AMR</i> (301) erroneously renders “fruitful” as “truthful”.]",
        type: "Diary",
        notes: null
    },
    {
        id: "xqtbgr",
        title: "Oxford Diary (9 April 1924 [<i>LP</i> 8:210])",
        printedIn: "Arend Smilde, “Why C.S. Lewis did not become a philosopher: Biographical Introduction” in “C.S. Lewis: Tutor and Lecturer in Philosophy: Philosophical Notes (1924),” eds. Norbert Feinendegen and Arend Smilde, <i>Inklings Studies Supplements</i>",
        issueOrVolume: "no. 2",
        pageRange: "65",
        year: 2021,
        monthAndDay: null,
        textProvided: "[In support of his intended application, Lewis received on 9 April]<br><br>a friendly note from Carritt enclosing a testimonial and saying “shall we at this stage drop the Mr.?”",
        type: "Diary",
        notes: null
    },
    {
        id: "acbuhk",
        title: "Oxford Diary (9 June 1924)",
        printedIn: "Arend Smilde, “Why C.S. Lewis did not become a philosopher: Biographical Introduction” in “C.S. Lewis: Tutor and Lecturer in Philosophy: Philosophical Notes (1924),” eds. Norbert Feinendegen and Arend Smilde, <i>Inklings Studies Supplements</i>",
        issueOrVolume: "no. 2",
        pageRange: "69",
        year: 2021,
        monthAndDay: null,
        textProvided: "worked on my paper in the morning",
        type: "Diary",
        notes: ["Identical to 7 June 1924 entry.", "Possibly a reference to his “Hegemony of Moral Value” paper."]
    },
    {
        id: "drbvbn",
        title: "Oxford Diary (22 March 1923)",
        printedIn: "Norbert Feinendegen, “‘A noise of great good coming’: C.S. Lewis’s <i>Dymer</i> as a Spiritual Autobiography,” <i>Sehnsucht: The C.S. Lewis Journal</i>",
        issueOrVolume: "vol. 17",
        pageRange: "32",
        year: 2023,
        monthAndDay: null,
        textProvided: "[In April 1922 Lewis began writing <i>Dymer</i>. On 22 March 1923, he noted in his diary that Canto V]<br><br>would always go wrong until I altered the contents–i.e., the episode does not run right and that is why the execution fails. I was struck with the truth of Aristotle’s dogma of ‘plot first.’",
        type: "Diary",
        notes: null
    },
    {
        id: "e86n38",
        title: "Oxford Diary (23 March 1923)",
        printedIn: "Norbert Feinendegen, “‘A noise of great good coming’: C.S. Lewis’s <i>Dymer</i> as a Spiritual Autobiography,” <i>Sehnsucht: The C.S. Lewis Journal</i>",
        issueOrVolume: "vol. 17",
        pageRange: "32 note 103",
        year: 2023,
        monthAndDay: null,
        textProvided: "[After composing Canto V of Dymer:]<br><br>I wish I knew how the next canto is to go",
        type: "Diary",
        notes: null
    }
];
